export const ListNegara = [
  { value: "AD", label: "ANDORRA" },
  { value: "AE", label: "UNITED ARAB EMIRATES" },
  { value: "AF", label: "AFGHANISTAN" },
  { value: "AG", label: "ANTIGUA AND BARBUDA" },
  { value: "AI", label: "ANGUILLA" },
  { value: "AL", label: "ALBANIA" },
  { value: "AM", label: "ARMENIA" },
  { value: "AN", label: "NETHERLANDS ANTILLES" },
  { value: "AO", label: "ANGOLA" },
  { value: "AQ", label: "ANTARCTICA" },
  { value: "AR", label: "ARGENTINA" },
  { value: "AS", label: "AMERICAN SAMOA" },
  { value: "AT", label: "AUSTRIA" },
  { value: "AU", label: "AUSTRALIA" },
  { value: "AW", label: "ARUBA" },
  { value: "AX", label: "ALAND ISLANDS" },
  { value: "AZ", label: "AZERBAIJAN" },
  { value: "BA", label: "BOSNIA AND HERZEGOVINA" },
  { value: "BB", label: "BARBADOS" },
  { value: "BD", label: "BANGLADESH" },
  { value: "BE", label: "BELGIUM" },
  { value: "BF", label: "BURKINA FASO" },
  { value: "BG", label: "BULGARIA" },
  { value: "BH", label: "BAHRAIN" },
  { value: "BI", label: "BURUNDI" },
  { value: "BJ", label: "BENIN" },
  { value: "BL", label: "SAINT BARTHELEMY" },
  { value: "BM", label: "BERMUDA" },
  { value: "BN", label: "BRUNEI DARUSSALAM" },
  { value: "BO", label: "BOLIVIA" },
  { value: "BQ", label: "BONAIRE, SINT EUSTATIUS AND SABA" },
  { value: "BR", label: "BRAZIL" },
  { value: "BS", label: "BAHAMAS" },
  { value: "BT", label: "BHUTAN" },
  { value: "BV", label: "BOUVET ISLAND" },
  { value: "BW", label: "BOTSWANA" },
  { value: "BY", label: "BELARUS" },
  { value: "BZ", label: "BELIZE" },
  { value: "CA", label: "CANADA" },
  { value: "CC", label: "COCOS (KEELING) ISLANDS" },
  { value: "CD", label: "CONGO, DEMOCRATIC REPUBLIC" },
  { value: "CF", label: "CENTRAL AFRICAN REPUBLIC" },
  { value: "CG", label: "CONGO" },
  { value: "CH", label: "SWITZERLAND" },
  { value: "CI", label: "COTE D'IVOIRE" },
  { value: "CK", label: "COOK ISLANDS" },
  { value: "CL", label: "CHILE" },
  { value: "CM", label: "CAMEROON" },
  { value: "CN", label: "CHINA" },
  { value: "CO", label: "COLOMBIA" },
  { value: "CR", label: "COSTA RICA" },
  { value: "CU", label: "CUBA" },
  { value: "CV", label: "CAPE VERDE" },
  { value: "CW", label: "CURACAO" },
  { value: "CX", label: "CHRISTMAS ISLAND" },
  { value: "CY", label: "CYPRUS" },
  { value: "CZ", label: "CZECH REPUBLIC" },
  { value: "DE", label: "GERMANY" },
  { value: "DK", label: "DENMARK" },
  { value: "DO", label: "DOMINICAN REPUBLIC" },
  { value: "DZ", label: "ALGERIA" },
  { value: "EC", label: "ECUADOR" },
  { value: "EG", label: "EGYPT" },
  { value: "ES", label: "SPAIN" },
  { value: "FI", label: "FINLAND" },
  { value: "FR", label: "FRANCE" },
  { value: "GB", label: "UNITED KINGDOM" },
  { value: "HK", label: "HONG KONG" },
  { value: "HU", label: "HUNGARY" },
  { value: "ID", label: "INDONESIA" },
  { value: "IN", label: "INDIA" },
  { value: "IT", label: "ITALY" },
  { value: "JP", label: "JAPAN" },
  { value: "KR", label: "KOREA, REPUBLIC OF" },
  { value: "MY", label: "MALAYSIA" },
  { value: "NL", label: "NETHERLANDS" },
  { value: "NZ", label: "NEW ZEALAND" },
  { value: "PH", label: "PHILIPPINES" },
  { value: "PK", label: "PAKISTAN" },
  { value: "RU", label: "RUSSIAN FEDERATION" },
  { value: "SA", label: "SAUDI ARABIA" },
  { value: "SG", label: "SINGAPORE" },
  { value: "TH", label: "THAILAND" },
  { value: "TR", label: "TURKEY" },
  { value: "TW", label: "TAIWAN" },
  { value: "US", label: "UNITED STATES" },
  { value: "VN", label: "VIET NAM" },
  { value: "ZA", label: "SOUTH AFRICA" },
  { value: "ZW", label: "ZIMBABWE" },
];