
export const ListKantor = [
            { "tableKey": "000000", "tableValue": "DJBC" },
            { "tableKey": "001000", "tableValue": "SEKRETARIAT" },
            { "tableKey": "001100", "tableValue": "TP BIDANG I" },
            { "tableKey": "001200", "tableValue": "TP BIDANG II" },
            { "tableKey": "001300", "tableValue": "TP BIDANG III" },
            { "tableKey": "001400", "tableValue": "DIREKTORAT KI" },
            { "tableKey": "001500", "tableValue": "DIREKTORAT KBP" },
            { "tableKey": "002000", "tableValue": "DIREKTORAT TEKNIS" },
            { "tableKey": "003000", "tableValue": "DIREKTORAT FASILITAS" },
            { "tableKey": "004000", "tableValue": "DIREKTORAT CUKAI" },
            { "tableKey": "005000", "tableValue": "DIREKTORAT P2" },
            { "tableKey": "006000", "tableValue": "DIREKTORAT AUDIT" },
            { "tableKey": "007000", "tableValue": "DIREKTORAT KIAL" },
            { "tableKey": "008000", "tableValue": "DIREKTORAT PPS" },
            { "tableKey": "009000", "tableValue": "DIREKTORAT IKC" },
            { "tableKey": "010000", "tableValue": "KANWIL SUMUT" },
            { "tableKey": "010100", "tableValue": "KPPBC KUALANAMU" },
            { "tableKey": "010700", "tableValue": "KPPBC ELAWAN" },
            { "tableKey": "010800", "tableValue": "KPPBC MEDAN" },
            { "tableKey": "010900", "tableValue": "KPPBC PANGKALAN SUSU" },
            { "tableKey": "011000", "tableValue": "KPPBC PEMATANGSIANTAR" },
            { "tableKey": "011100", "tableValue": "KPPBC TELUK NIBUNG" },
            { "tableKey": "011200", "tableValue": "KPPBC KUALA TANJUNG" },
            { "tableKey": "011300", "tableValue": "KPPBC SIBOLGA" },
            { "tableKey": "011500", "tableValue": "KPPBC TELUK BAYUR" },
            { "tableKey": "011600", "tableValue": "BLBC KELAS II MEDAN" },
            { "tableKey": "020000", "tableValue": "KANWIL KHUSUS KEPRI" },
            { "tableKey": "020100", "tableValue": "KPPBC TBK" },
            { "tableKey": "020200", "tableValue": "KPPBC SAMBU BELAKANG PADANG" },
            { "tableKey": "020300", "tableValue": "KPPBC SELAT PANJANG" },
            { "tableKey": "020400", "tableValue": "KPU BATAM" },
            { "tableKey": "020500", "tableValue": "KPPBC TANJUNG PINANG" },
            { "tableKey": "020800", "tableValue": "KPPBC DABO SINGKEP" },
            { "tableKey": "020900", "tableValue": "KPPBC DUMAI" },
            { "tableKey": "021000", "tableValue": "KPPBC BAGAN SIAPIAPI" },
            { "tableKey": "021100", "tableValue": "KPPBC BENGKALIS" },
            { "tableKey": "021200", "tableValue": "KPPBC PEKANBARU" },
            { "tableKey": "021300", "tableValue": "KPPBC SIAK SRI INDRAPURA" },
            { "tableKey": "021500", "tableValue": "KPPBC TEMBILAHAN" },
            { "tableKey": "021700", "tableValue": "KPPBC TAREMPA" },
            { "tableKey": "021800", "tableValue": "PANGSAROP BATAM" },
            { "tableKey": "021900", "tableValue": "PANGSAROP  TANJUNG BALAI KARIMUN" },
            { "tableKey": "030000", "tableValue": "KANWIL SUMBAGTIM" },
            { "tableKey": "030100", "tableValue": "KPPBC PALEMBANG" },
            { "tableKey": "030200", "tableValue": "KPPBC BENGKULU" },
            { "tableKey": "030300", "tableValue": "KPPBC PANGKALPINANG" },
            { "tableKey": "030500", "tableValue": "KPPBC TANJUNGPANDAN" },
            { "tableKey": "030600", "tableValue": "KPPBC JAMBI" },
            { "tableKey": "030700", "tableValue": "KPPBC BANDAR LAMPUNG" },
            { "tableKey": "040000", "tableValue": "KANWIL JAKARTA" },
            { "tableKey": "040300", "tableValue": "KPU TANJUNG PRIOK" },
            { "tableKey": "040400", "tableValue": "KPPBC JAKARTA" },
            { "tableKey": "040500", "tableValue": "BLBC KELAS I JAKARTA" },
            { "tableKey": "040600", "tableValue": "KPPBC KANTOR POS PASAR BARU" },
            { "tableKey": "040700", "tableValue": "PANGSAROP TANJUNG PRIOK" },
            { "tableKey": "050000", "tableValue": "KANWIL JABAR" },
            { "tableKey": "050100", "tableValue": "KPU  SOEKARNO-HATTA" },
            { "tableKey": "050300", "tableValue": "KPPBC  BOGOR" },
            { "tableKey": "050400", "tableValue": "KPPBC TMP MERAK" },
            { "tableKey": "050500", "tableValue": "KPPBC BANDUNG" },
            { "tableKey": "050600", "tableValue": "KPPBC TASIKMALAYA" },
            { "tableKey": "050700", "tableValue": "KPPBC CIREBON" },
            { "tableKey": "050800", "tableValue": "KPPBC PURWAKARTA" },
            { "tableKey": "050900", "tableValue": "KPPBC BEKASI" },
            { "tableKey": "051000", "tableValue": "KPPBC IKARANG" },
            { "tableKey": "060000", "tableValue": "KANWIL JATENG DIY" },
            { "tableKey": "060100", "tableValue": "KPPBC TMP TANJUNG EMAS" },
            { "tableKey": "060200", "tableValue": "KPPBC PEKALONGAN" },
            { "tableKey": "060300", "tableValue": "KPPBC TMC KUDUS" },
            { "tableKey": "060400", "tableValue": "KPPBC CILACAP" },
            { "tableKey": "060600", "tableValue": "KPPBC SURAKARTA" },
            { "tableKey": "060700", "tableValue": "KPPBC YOGYAKARTA" },
            { "tableKey": "060800", "tableValue": "KPPBC SEMARANG" },
            { "tableKey": "061000", "tableValue": "KPPBC TEGAL" },
            { "tableKey": "061100", "tableValue": "KPPBC MAGELANG" },
            { "tableKey": "062000", "tableValue": "KPPBC PURWOKERTO" },
            { "tableKey": "070000", "tableValue": "KANWIL JATIM I" },
            { "tableKey": "070100", "tableValue": "KPPBC TMP TANJUNG PERAK" },
            { "tableKey": "070200", "tableValue": "KPPBC MADURA" },
            { "tableKey": "070300", "tableValue": "KPPBC GRESIK" },
            { "tableKey": "070400", "tableValue": "KPPBC BOJONEGORO" },
            { "tableKey": "070500", "tableValue": "KPPBC TMP JUANDA" },
            { "tableKey": "070600", "tableValue": "KPPBC TMC MALANG" },
            { "tableKey": "070700", "tableValue": "KPPBC BLITAR" },
            { "tableKey": "070800", "tableValue": "KPPBC TMC KEDIRI" },
            { "tableKey": "070900", "tableValue": "KPPBC TULUNG AGUNG" },
            { "tableKey": "071000", "tableValue": "KPPBC MADIUN" },
            { "tableKey": "071100", "tableValue": "KPPBC JEMBER" },
            { "tableKey": "071200", "tableValue": "KPPBC PROBOLINGGO" },
            { "tableKey": "071300", "tableValue": "KPPBC PASURUAN" },
            { "tableKey": "071400", "tableValue": "BLBC KELAS II SURABAYA" },
            { "tableKey": "071500", "tableValue": "KPPBC SIDOARJO" },
            { "tableKey": "080000", "tableValue": "KANWIL BALI, NTB DAN NTT" },
            { "tableKey": "080100", "tableValue": "KPPBC TMP NGURAH RAI" },
            { "tableKey": "080200", "tableValue": "KPPBC DENPASAR" },
            { "tableKey": "080300", "tableValue": "KPPBC MATARAM" },
            { "tableKey": "080400", "tableValue": "KPPBC SUMBAWA" },
            { "tableKey": "080500", "tableValue": "KPPBC KUPANG" },
            { "tableKey": "080700", "tableValue": "KPPBC MAUMERE" },
            { "tableKey": "081200", "tableValue": "KPPBC BENOA" },
            { "tableKey": "081300", "tableValue": "KPPBC ATAPUPU" },
            { "tableKey": "081400", "tableValue": "KPPBC ATAMBUA" },
            { "tableKey": "090000", "tableValue": "KANWIL KALBAGBAR" },
            { "tableKey": "090100", "tableValue": "KPPBC PONTIANAK" },
            { "tableKey": "090200", "tableValue": "KPPBC ENTIKONG" },
            { "tableKey": "090400", "tableValue": "KPPBC KETAPANG" },
            { "tableKey": "090500", "tableValue": "KPPBC SINTETE" },
            { "tableKey": "090700", "tableValue": "KPPBC SAMPIT" },
            { "tableKey": "090800", "tableValue": "KPPBC PANGKALAN BUN" },
            { "tableKey": "090900", "tableValue": "KPPBC PULANG PISAU" },
            { "tableKey": "091000", "tableValue": "KPPBC NANGA BADAU" },
            { "tableKey": "092000", "tableValue": "KPPBC JAGOI BABANG" },
            { "tableKey": "100000", "tableValue": "KANWIL KALBAGTIM" },
            { "tableKey": "100100", "tableValue": "KPPBC BANJARMASIN" },
            { "tableKey": "100200", "tableValue": "KPPBC KOTABARU" },
            { "tableKey": "100300", "tableValue": "KPPBC BALIKPAPAN" },
            { "tableKey": "100500", "tableValue": "KPPBC SAMARINDA" },
            { "tableKey": "100600", "tableValue": "KPPBC BONTANG" },
            { "tableKey": "100800", "tableValue": "KPPBC TARAKAN" },
            { "tableKey": "100900", "tableValue": "KPPBC NUNUKAN" },
            { "tableKey": "101000", "tableValue": "KPPBC SANGATTA" },
            { "tableKey": "110000", "tableValue": "KANWIL SULBAGSEL" },
            { "tableKey": "110100", "tableValue": "KPPBC MAKASSAR" },
            { "tableKey": "110300", "tableValue": "KPPBC PAREPARE" },
            { "tableKey": "110400", "tableValue": "KPPBC MALILI" },
            { "tableKey": "110500", "tableValue": "KPPBC BAJOE" },
            { "tableKey": "110600", "tableValue": "KPPBC KENDARI" },
            { "tableKey": "110700", "tableValue": "KPPBC POMALAA" },
            { "tableKey": "110800", "tableValue": "KPPBC PANTOLOAN" },
            { "tableKey": "110900", "tableValue": "KPPBC MOROWALI" },
            { "tableKey": "111000", "tableValue": "KPPBC LUWUK" },
            { "tableKey": "111100", "tableValue": "KPPBC BITUNG" },
            { "tableKey": "111200", "tableValue": "KPPBC MANADO" },
            { "tableKey": "111300", "tableValue": "KPPBC GORONTALO" },
            { "tableKey": "111400", "tableValue": "PANGSAROP PANTOLOAN" },
            { "tableKey": "120000", "tableValue": "KANWIL MALUKU" },
            { "tableKey": "120100", "tableValue": "KPPBC AMBON" },
            { "tableKey": "120200", "tableValue": "KPPBC TERNATE" },
            { "tableKey": "120300", "tableValue": "KPPBC SORONG" },
            { "tableKey": "120400", "tableValue": "KPPBC MANOKWARI" },
            { "tableKey": "120500", "tableValue": "KPPBC FAK-FAK" },
            { "tableKey": "120600", "tableValue": "KPPBC JAYAPURA" },
            { "tableKey": "120700", "tableValue": "KPPBC MERAUKE" },
            { "tableKey": "120800", "tableValue": "KPPBC AMAMAPARE" },
            { "tableKey": "120900", "tableValue": "KPPBC BIAK" },
            { "tableKey": "121000", "tableValue": "KPPBC TUAL" },
            { "tableKey": "121100", "tableValue": "PANGSAROP SORONG" },
            { "tableKey": "122000", "tableValue": "KPPBC BINTUNI" },
            { "tableKey": "122100", "tableValue": "KPPBC KAIMANA" },
            { "tableKey": "122200", "tableValue": "KPPBC NABIRE" },
            { "tableKey": "122300", "tableValue": "KPPBC BABO" },
            { "tableKey": "130000", "tableValue": "KANWIL ACEH" },
            { "tableKey": "130100", "tableValue": "KPPBC BANDA ACEH" },
            { "tableKey": "130300", "tableValue": "KPPBC SABANG" },
            { "tableKey": "130400", "tableValue": "KPPBC MEULABOH" },
            { "tableKey": "130500", "tableValue": "KPPBC LHOKSEUMAWE" },
            { "tableKey": "130600", "tableValue": "KPPBC KUALA LANGSA" },
            { "tableKey": "140000", "tableValue": "KANWIL RIAU" },
            { "tableKey": "150000", "tableValue": "KANWIL BANTEN" },
            { "tableKey": "150300", "tableValue": "KPPBC TANGERANG" },
            { "tableKey": "160000", "tableValue": "KANWIL JATIM II" },
            { "tableKey": "160200", "tableValue": "KPPBC MARUNDA" },
            { "tableKey": "160700", "tableValue": "KPPBC BANYUWANGI" },
            { "tableKey": "170000", "tableValue": "KANWIL SUMBAGBAR" },
            { "tableKey": "180000", "tableValue": "KANWIL KALBAGSEL" },
            { "tableKey": "180100", "tableValue": "KPPBC Nashta" },
            { "tableKey": "180200", "tableValue": "KPPBC Nashta" },
            { "tableKey": "190000", "tableValue": "KANWIL SULBAGTARA" },
            { "tableKey": "200000", "tableValue": "KANWIL KHUSUS PAPUA" },
            { "tableKey": "760000", "tableValue": "PUSDIKLAT BEA DAN CUKAI" },
            { "tableKey": "999999", "tableValue": "UNIT LAIN DI LUAR DJBC" }
]