export const ListPelabuhan = [
    { value: "IDTPP", label: "IDTPP - TANJUNG PRIOK" },
    { value: "IDTES", label: "IDTES - TANJUNG EMAS " },
    { value: "IDSUB", label: "IDSUB - SURABAYA/JUANDA(U) " },
    { value: "IDSRG", label: "IDSRG - SEMARANG/AHMAD YANI " },
    { value: "IDTPE", label: "IDTPE - TANJUNG PERAK " },
    { value: "IDSOC", label: "IDSOC - SOLO CITY " },
    { value: "IDCGK", label: "IDCGK - CENGKARENG " },
    { value: "CNSHA", label: "CNSHA - SHANGHAI CHINA " },
    { value: "SGSIN", label: "SGSIN - SINGAPORE " },
    { value: "HKHKG", label: "HKHKG - HONG KONG " },
    { value: "MYPEN", label: "MYPEN - MALAYSIA PENANG " },
    { value: "CNTAO", label: "CNTAO - CHINA QING DAO " },
    { value: "AUADL", label: "AUADL - Adelaide" },
    { value: "AUBNE", label: "AUBNE - Brisbane" },
    { value: "AUBWU", label: "AUBWU - Bankstown" },
    { value: "AUCRG", label: "AUCRG - Caringbah" },
    { value: "AUMEL", label: "AUMEL - Melbourne" },
    { value: "AUPER", label: "AUPER - Perth" },
    { value: "AUSYD", label: "AUSYD - Sydney" },
    { value: "AUVIW", label: "AUVIW - Villawood/Sydney" },
    { value: "BDDAC", label: "BDDAC - Dhaka" },
    { value: "CNBJS", label: "CNBJS - Beijing" },
    { value: "CNCAN", label: "CNCAN - Guangzhou" },
    { value: "CNCZX", label: "CNCZX - Changzhou" },
    { value: "CNDAX", label: "CNDAX - Daxian" },
    { value: "CNDGG", label: "CNDGG - Dongguan" },
    { value: "CNDGM", label: "CNDGM - Dongguan Apt" },
    { value: "CNFOC", label: "CNFOC - Fuzhou" },
    { value: "CNHGH", label: "CNHGH - Hangzhou" },
    { value: "CNJGY", label: "CNJGY - Jiangyin" },
    { value: "CNJIA", label: "CNJIA - Jiangyin" },
    { value: "CNJIX", label: "CNJIX - Jiaxing" },
    { value: "CNJJI", label: "CNJJI - Jinjiang" },
    { value: "CNJJN", label: "CNJJN - Jinjiang" },
    { value: "CNKMG", label: "CNKMG - Kunming" },
    { value: "CNNGB", label: "CNNGB - Ningbo" },
    { value: "CNNSA", label: "CNNSA - Nansha" },
    { value: "CNNTG", label: "CNNTG - Nantong" },
    { value: "CNPDG", label: "CNPDG - Shanghai Pu Dong" },
    { value: "CNPEK", label: "CNPEK - Beijing Capital International Airport" },
    { value: "CNPVG", label: "CNPVG - Shanghai Pu Dong Apt" },
    { value: "CNSAD", label: "CNSAD - Shandong" },
    { value: "CNSHA", label: "CNSHA - Shanghai" },
    { value: "CNSHK", label: "CNSHK - Shekou" },
    { value: "CNSHS", label: "CNSHS - Shashi" },
    { value: "CNSUZ", label: "CNSUZ - Suzhou" },
    { value: "CNSWA", label: "CNSWA - Shantou" },
    { value: "CNSXG", label: "CNSXG - Shaoxing" },
    { value: "CNSYM", label: "CNSYM - Simao" },
    { value: "CNSZH", label: "CNSZH - Shenzhen" },
    { value: "CNSZP", label: "CNSZP - SHENZHEN" },
    { value: "CNSZX", label: "CNSZX - Shenzhen" },
    { value: "CNTAO", label: "CNTAO - Qingdao" },
    { value: "CNTCG", label: "CNTCG - Qoqek Apt" },
    { value: "CNWUH", label: "CNWUH - Wuhan" },
    { value: "CNWUX", label: "CNWUX - Wuxi" },
    { value: "CNXIS", label: "CNXIS - Xiaoshan" },
    { value: "CNXMN", label: "CNXMN - Xiamen" },
    { value: "CNYZH", label: "CNYZH - Yangzhou" },
    { value: "CNZAT", label: "CNZAT - Zhaotong Apt" },
    { value: "CNZIB", label: "CNZIB - Zibo" },
    { value: "CNZJG", label: "CNZJG - Zhangjiagang" },
    { value: "CNZUH", label: "CNZUH - Zhuhai" },
    { value: "DECGN", label: "DECGN - Koln" },
    { value: "DEFMM", label: "DEFMM - Frammersbach" },
    { value: "DELAG", label: "DELAG - Landsberg" },
    { value: "DEMUC", label: "DEMUC - Munchen" },
    { value: "ESBCN", label: "ESBCN - Barcelona" },
    { value: "FJNAN", label: "FJNAN - Nadi" },
    { value: "FJSUV", label: "FJSUV - Fiji Suva" },
    { value: "GBBHX", label: "GBBHX - BIRMINGHAM APT" },
    { value: "GBLBA", label: "GBLBA - Leeds" },
    { value: "GBLCY", label: "GBLCY - Lochgelly" },
    { value: "GBLGP", label: "GBLGP - London Gateway Port" },
    { value: "GBLON", label: "GBLON - London" },
    { value: "GBMAN", label: "GBMAN - MANCHESTER-RINGWAY APT"},
    { value: "GBNCL", label: "GBNCL - Newcastle Upon Tyne" },
    { value: "GBSOU", label: "GBSOU - Southampton" },
    { value: "GBZLS", label: "GBZLS - Zeals" },
    { value: "HKGOM", label: "HKGOM - Hung Hom" },
    { value: "HKHKG", label: "HKHKG - Hong Kong" },
    { value: "HKKCO", label: "HKKCO - Kwai Chung" },
    { value: "HKKTG", label: "HKKTG - Kwun Tong" },
    { value: "HKKWN", label: "HKKWN - Kowloon" },
    { value: "HKMUN", label: "HKMUN - Tuen Mun" },
    { value: "HKZTW", label: "HKZTW - Tsuen Wan" },
    { value: "INDEL", label: "INDEL - Delhi" },
    { value: "INHIP", label: "INHIP - Himachal Pradesh" },
    { value: "INMUB", label: "INMUB - Mumbai" },
    { value: "INNSA", label: "INNSA - Jawaharlal Nehru (Nhava S" },
    { value: "INPAV", label: "INPAV - Pipavav (Victor) Port" },
    { value: "INPNQ", label: "INPNQ - Pune" },
    { value: "INTAE", label: "INTAE - Thane" },
    { value: "ITBGY", label: "ITBGY - Orio Al Serio" },
    { value: "ITCAX", label: "ITCAX - Casella/Genova" },
    { value: "ITFLR", label: "ITFLR - Firenze" },
    { value: "ITMXP", label: "ITMXP - Malpensa Milan" },
    { value: "ITROM", label: "ITROM - Roma" },
    { value: "ITVCE", label: "ITVCE - Venezia" },
    { value: "JPKIX", label: "JPKIX - Kansai Int Apt" },
    { value: "JPNGO", label: "JPNGO - Nagoya, Aichi" },
    { value: "JPNGY", label: "JPNGY - Nagoya, Oita" },
    { value: "JPNRT", label: "JPNRT - Narita Apt/Tokyo" },
    { value: "JPOSA", label: "JPOSA - Osaka" },
    { value: "JPTYO", label: "JPTYO - Tokyo" },
    { value: "JPUKB", label: "JPUKB - Kobe" },
    { value: "KHPNH", label: "KHPNH - Phnom Pehn" },
    { value: "KRICN", label: "KRICN - Incheon Intl Apt/Seoul" },
    { value: "KROSN", label: "KROSN - Osan" },
    { value: "KRPUS", label: "KRPUS - Busan (ex Pusan)" },
    { value: "KRSEL", label: "KRSEL - Seoul - Kimpo apt" },
    { value: "KRTAE", label: "KRTAE - Daegu (ex Taegu)" },
    { value: "MYKUL", label: "MYKUL - Kuala Lumpur" },
    { value: "MYPEN", label: "MYPEN - Penang (Georgetown)" },
    { value: "MYSZB", label: "MYSZB - Subang Kuala Lumpur Airport" },
    { value: "MYWSP", label: "MYWSP - Westport/Port Klang" },
    { value: "NLAMS", label: "NLAMS - Amsterdam" },
    { value: "NLGOO", label: "NLGOO - Goor" },
    { value: "NLLEY", label: "NLLEY - Lelystad" },
    { value: "NZAKA", label: "NZAKA - Akaroa" },
    { value: "NZAKL", label: "NZAKL - Auckland" },
    { value: "NZLYT", label: "NZLYT - Lyttelton" },
    { value: "NZTRG", label: "NZTRG - Tauranga" },
    { value: "NZWLG", label: "NZWLG - Wellington" },
    { value: "PKKHI", label: "PKKHI - Karachi" },
    { value: "PKLHE", label: "PKLHE - Lahore" },
    { value: "PTOPO", label: "PTOPO - Porto" },
    { value: "SGSIN", label: "SGSIN - Singapore" },
    { value: "THBAO", label: "THBAO - Ban Mak Khaen" },
    { value: "THBKK", label: "THBKK - Bangkok" },
    { value: "THLCH", label: "THLCH - Laem Chabang" },
    { value: "TRIST", label: "TRIST - Istanbul" },
    { value: "TWKHH", label: "TWKHH - Kaohsiung" },
    { value: "TWTNN", label: "TWTNN - Tainan" },
    { value: "TWTPE", label: "TWTPE - Taipei" },
    { value: "TWTTT", label: "TWTTT - Taitung" },
    { value: "TWTXG", label: "TWTXG - Taichung" },
    { value: "USCIB", label: "USCIB - Casselberry" },
    { value: "USCLT", label: "USCLT - Charlotte" },
    { value: "USLAX", label: "USLAX - Los Angeles" },
    { value: "USMTP", label: "USMTP - Montauk" },
    { value: "USNYC", label: "USNYC - New York" },
    { value: "USSMO", label: "USSMO - Santa Monica" },
    { value: "USTSS", label: "USTSS - Curtiss" },
    { value: "VNDAD", label: "VNDAD - Da Nang" },
    { value: "VNHAN", label: "VNHAN - Hanoi" },
    { value: "VNHPH", label: "VNHPH - Haiphong" },
    { value: "VNSGN", label: "VNSGN - Ho Chi Minh City" },
    { value: "VNTNT", label: "VNTNT - Tay Ninh" },
  ];