export const TPS_BY_PELABUHAN: Record<string, { value: string; label: string }[]> = {
  IDTES: [
    { value: "CFS", label: "CFS - GUDANG CARGO" },
    { value: "GANI", label: "GANI - GUDANG A. YANI" },
    { value: "GDHL", label: "GDHL - GUDANG BIROTIKA SEMESTA" },
    { value: "UTPK", label: "UTPK - UNIT TERMINAL PETI KEMAS" },
  ],

  IDSRG: [
    { value: "CFS", label: "CFS - GUDANG CARGO" },
    { value: "GANI", label: "GANI - GUDANG A. YANI" },
    { value: "GDHL", label: "GDHL - GUDANG BIROTIKA SEMESTA" },
    { value: "UTPK", label: "UTPK - UNIT TERMINAL PETI KEMAS" },
  ],

  IDCGK: [
    { value: "BML1", label: "BML1 - PT BERDIRI MATAHARI LOGISTIK" },
        { value: "CAR1", label: "CAR1 - PT CARDIG INTERNASIONAL SUPPORT" },
        { value: "CIMP", label: "CIMP - GUDANG CARDIG IMPOR" },
        { value: "CJGL", label: "CJGL - CJ-GLS" },
        { value: "CLI1", label: "CLI1 - TPS-TNS CITRABATI LOGISTIK INTERNASIONAL" },
        { value: "GAJT", label: "GAJT - GARUDA INDONESIA PJT" },
        { value: "GATE", label: "GATE - GHITA AVIA TRANS" },
        { value: "GATI", label: "GATI - GHITA AVIA TRANS" },
        { value: "GBDL", label: "GBDL - PT. BANGUN DESA LOGISTINDO" },
        { value: "GBGD", label: "GBGD - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "GBGF", label: "GBGF - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "GBGT", label: "GBGT - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "GCPL", label: "GCPL - GUDANG C & P LOGISTICS INDONES" },
        { value: "GDHL", label: "GDHL - GUDANG DHL" },
        { value: "GDJT", label: "GDJT - WAHANA DIRGANTARA INDONESIA" },
        { value: "GDWD", label: "GDWD - Gudang Wahan Dirgantara" },
        { value: "GDWF", label: "GDWF - GUDANG WAHANA DIRGANTARA INDONESIA" },
        { value: "GDWI", label: "GDWI - GUDANG WAHANA DIRGANTARA IMPOR" },
        { value: "GELK", label: "GELK - GARUDA ENERGI LOGISTIK KOMERSIAL" },
        { value: "GGMF", label: "GGMF - GARUDA MAINTENANCE FACILITIES" },
        { value: "GGWI", label: "GGWI - GUDANG GEODIS WILSON INDONESIA" },
        { value: "GIBS", label: "GIBS - TPS-TNS INTI BANGUN SELARAS" },
        { value: "GIMP", label: "GIMP - GUDANG GARUDA IMPOR" },
        { value: "GJDC", label: "GJDC - TPS-TNS DHL PT. BIROTIKA SEMESTA" },
        { value: "GLFC", label: "GLFC - TPS-TNS GLOBAL FREIGHT CONSOLIDATAMA" },
        { value: "DS02", label: "DS02 - PT DSV TRANSPORT INDONESIA" },
        { value: "DS03", label: "DS03 - PT DSV TRANSPORT INDONESIA" },
        { value: "DS04", label: "DS04 - PT DSV TRANSPORT INDONESIA" },
        { value: "DXKT", label: "DXKT - TPS-PT. DEXTER EUREKATAMA" },
        { value: "EPIA", label: "EPIA - PT. EKSPRES PARCEL INDONESIA" },
        { value: "FEDX", label: "FEDX - GUDANG FEDEX" },
        { value: "FM01", label: "FM01 - PT. FM GLOBAL LOGISTICS" },
        { value: "G001", label: "G001 - GROUP JAS" },
        { value: "G002", label: "G002 - GROUP TNS" },
        { value: "G003", label: "G003 - GROUP BGD" },
        { value: "APKE", label: "APKE - ANGKASA PURA KARGO" },
        { value: "APKI", label: "APKI - ANGKASA PURA KARGO" },
        { value: "APRI", label: "APRI - TPS-PT. ANGKASA PURA II - IMPOR" },
        { value: "KENA", label: "KENA - PT KARGO EXPRESS NUSANTARA" },
        { value: "LE01", label: "LE01 - TPS LINTAS EKSPRES N.C." },
        { value: "LOGW", label: "LOGW - TPS-TNS GUDANG LOGWIN AIR & OCEAN INDONESIA" },
        { value: "LWPH", label: "LWPH - PT Logwin Air And Ocean Indonesia" },
        { value: "MATR", label: "MATR - MITRA ATLANTIK TRANSINDO" },
        { value: "MSA1", label: "MSA1 - PT MONANG SIANIPAR ABADI" },
        { value: "MSA4", label: "MSA4 - PT. MONANG SIANIPAR ABADI" },
        { value: "MSA5", label: "MSA5 - PT MONANG SIANIPAR ABADI" },
        { value: "MUE1", label: "MUE1 - PT. MITRA UTAMA EXPRESS" },
        { value: "NFII", label: "NFII - PT NAKU FREIGHT INDONESIA" },
        { value: "NRGL", label: "NRGL - PT NNR RPX GLOBAL LOGISTICS INDONESIA" },
        { value: "PGTI", label: "PGTI - PT PRIMA GLOBAL TRANS" },
        { value: "GPPL", label: "GPPL - PANAH PERDANA LOGISINDO" },
        { value: "GPRA", label: "GPRA - GAPURA ANGKASA" },
        { value: "GUCT", label: "GUCT - TPS Unggul Cipta Trans" },
        { value: "GUEL", label: "GUEL - TPS PT. UNIVERSAL EKSPRES LOGISTINDO" },
        { value: "IBS2", label: "IBS2 - INTI BANGUN SELARAS 2" },
        { value: "IGLB", label: "IGLB - TPS-TNS INTI GLOBAL LOGISTICS" },
        { value: "IMSI", label: "IMSI - IMS LOGISTICS INDONESIA" },
        { value: "IPRT", label: "IPRT - PT. PERIGI RAJA TERPADU" },
        { value: "JGE1", label: "JGE1 - PT. JUSTINDO GLOBAL EKSPRES" },
        { value: "JRDN", label: "JRDN - TPS-TNS JARINGAN DINAMIKA" },
        { value: "KBPI", label: "KBPI - PT KARYA BAKTI PERSADA CARGO" },
        { value: "PX01", label: "PX01 - PT. PANTOS EXPRESS" },
        { value: "TMNI", label: "TMNI - TPS-TNS MAKTRANS NUSA INDAH" },
        { value: "TPEI", label: "TPEI - TAS PUNINAR EXPRESS INDONESIA" },
        { value: "TRKI", label: "TRKI - PT. TRANS KARGO INTERNASIONAL" },
        { value: "TSLM", label: "TSLM - TPS-TNS SKY LIGHT MULTITRADA" },
        { value: "TUTI", label: "TUTI - TPS-UNION TRANS INTERNUSA" },
        { value: "TZ01", label: "TZ01 - TPS-TNS ABX TABITHA LOGISTIK" },
        { value: "UELI", label: "UELI - PT UNIVERSAL EKSPRES LOGISTINDO" },
        { value: "UNEX", label: "UNEX - GUDANG UNEX INTI INDONESIA" },
        { value: "VALI", label: "VALI - TPS-TNS  VINFLAIR LOGISTICS INDONESIA" },
        { value: "YIFI", label: "YIFI - PT. YAMATO INDONESIA FORWARDING" },
        { value: "DS06", label: "DS06 - PT DSV TRANSPORT INDONESIA" },
        { value: "JWI2", label: "JWI2 - PT JAS WORLDWIDE INDONESIA" },
        { value: "SKK2", label: "SKK2 - PT SINERGI KARYA KHARISMA" },
        { value: "JGE2", label: "JGE2 - PT Justindo Global Ekspres" },
        { value: "SII2", label: "SII2 - TPS-TNS PT Senator International Indonesia" },
        { value: "SKK1", label: "SKK1 - PT. SINERGI KARYA KHARISMA" },
        { value: "SLII", label: "SLII - PT SINERGI LOGISTIK INDONESIA" },
        { value: "SPLI", label: "SPLI - TPS-TNS SPEEDMARK LOGISTIK INDONESIA" },
        { value: "TA01", label: "TA01 - TPS-TNS NIPPON EXPRESS INDONES" },
        { value: "TA02", label: "TA02 - TPS-TNS SCHENKER PETROLOG U" },
        { value: "TA03", label: "TA03 - TPS-TNS UNIAIR INDOTAMA" },
        { value: "TA04", label: "TA04 - TPS-TNS DFDS" },
        { value: "TA05", label: "TA05 - TPS-TNS PANALPINA NUSAJAYA TRN" },
        { value: "TA08", label: "TA08 - TPS-TNS BAX GLOBAL LOGISTIK" },
        { value: "TA10", label: "TA10 - TPS-TNS K LINE AIR SERVICE INDONESIA" },
        { value: "TA11", label: "TA11 - TPS-TNS FAJAR INSAN NUSANTARA" },
        { value: "TA12", label: "TA12 - TPS-TNS TABITHA EXPRESS" },
        { value: "TA13", label: "TA13 - TPS-TNS TABHITA EXPRESS" },
        { value: "TA15", label: "TA15 - TPS-TNS GREEN AIR PACIFIC" },
        { value: "TB01", label: "TB01 - TPS-TNS FRITZ LOGISTICS INDONE" },
        { value: "TB05", label: "TB05 - TPS-TNS DANZAS SARANA PERKASA" },
        { value: "TB06", label: "TB06 - TPS-TNS EXPEDITOR INDONESIA" },
        { value: "TB08", label: "TB08 - TPS-TNS UNGGUL CIPTA TRANS" },
        { value: "TB09", label: "TB09 - TPS-TNS MONANG SIANIPAR ABADI" },
        { value: "TB10", label: "TB10 - TPS-TNS RITRA CARGO INDONESIA" },
        { value: "TB11", label: "TB11 - TPS-TNS SKYPAK INT. (TNT)" },
        { value: "TB12", label: "TB12 - TPS-TNS GEOLOGISTICS IND. P" },
        { value: "TB13", label: "TB13 - TPS-TNS KINTETSU WORLD EX. IND" },
        { value: "TB14", label: "TB14 - PT PELANGI SEMESTA" },
        { value: "TB15", label: "TB15 - TPS-TNS GUDANG CARDIG LOGISTICS INDONESIA" },
        { value: "TB21", label: "TB21 - PT SKYPAK INTERNATIONAL" },
        { value: "TE03", label: "TE03 - TPS-TNS PRIMA INTERNATIONAL C." },
        { value: "TE08", label: "TE08 - TPS-TNS YUSEN AIR & SEA INDON" },
        { value: "TE11", label: "TE11 - TPS-TNS SDV LOGISTICS INDONESIA" },
        { value: "TJ10", label: "TJ10 - TPS-TNS CERINDO TRANSPORT LOGISTIK" },
        { value: "PNMI", label: "PNMI - TPS-TNS PUNINAR MSE INDONESIA" },
        { value: "POSE", label: "POSE - GUDANG TPS POS EKSPOR" },
        { value: "POSI", label: "POSI - GUDANG TPS POS IMPOR" },
  ],


  IDTPP: [
    { value: "101U", label: "BML1 - PT BERDIRI MATAHARI LOGISTIK" },
        { value: "106X", label: "CAR1 - PT CARDIG INTERNASIONAL SUPPORT" },
        { value: "213", label: "CIMP - GUDANG CARDIG IMPOR" },
        { value: "214X", label: "CJGL - CJ-GLS" },
        { value: "215X", label: "CLI1 - TPS-TNS CITRABATI LOGISTIK INTERNASIONAL" },
        { value: "221X", label: "GAJT - GARUDA INDONESIA PJT" },
        { value: "223X", label: "GATE - GHITA AVIA TRANS" },
        { value: "909", label: "GATI - GHITA AVIA TRANS" },
        { value: "AB16", label: "GBDL - PT. BANGUN DESA LOGISTINDO" },
        { value: "BERD", label: "GBGD - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "CART", label: "GBGF - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "CDP1", label: "GBGT - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "GCFS", label: "GCPL - GUDANG C & P LOGISTICS INDONES" },
        { value: "DHAR", label: "GDHL - GUDANG DHL" },
        { value: "AIRN", label: "GDJT - WAHANA DIRGANTARA INDONESIA" },
        { value: "ARN1", label: "GDWD - GUDANG WAHANA DIRGANTARA" },
        { value: "ARN3", label: "GDWF - GUDANG WAHANA DIRGANTARA INDONESIA" },
        { value: "BAK1", label: "GDWI - GUDANG WAHANA DIRGANTARA IMPOR" },
        { value: "BAND", label: "GELK - GARUDA ENERGI LOGISTIK KOMERSIAL" },
        { value: "KOJA", label: "GGMF - GARUDA MAINTENANCE FACILITIES" },
        { value: "KTM0", label: "GGWI - GUDANG GEODIS WILSON INDONESIA" },
        { value: "MKT1", label: "GIBS - TPS-TNS INTI BANGUN SELARAS" },
        { value: "MTI1", label: "GIMP - GUDANG GARUDA IMPOR" },
        { value: "NCT1", label: "GJDC - TPS-TNS DHL PT. BIROTIKA SEMESTA" },
        { value: "NPCT", label: "GLFC - TPS-TNS GLOBAL FREIGHT CONSOLIDATAMA" },
        { value: "PESA", label: "DS02 - PT DSV TRANSPORT INDONESIA" },
        { value: "GRHA", label: "DS03 - PT DSV TRANSPORT INDONESIA" },
        { value: "GSRA", label: "DS04 - PT DSV TRANSPORT INDONESIA" },
        { value: "ISM1", label: "DXKT - TPS-PT. DEXTER EUREKATAMA" },
        { value: "RAYA", label: "EPIA - PT. EKSPRES PARCEL INDONESIA" },
        { value: "SDKP", label: "FEDX - GUDANG FEDEX" },
        { value: "TLKP", label: "FM01 - PT. FM GLOBAL LOGISTICS" },
        { value: "TMAL", label: "G001 - GROUP JAS" },
        { value: "TND2", label: "G002 - GROUP TNS" },
        { value: "TNDO", label: "G003 - GROUP BGD" },
        { value: "TPK1", label: "APKE - ANGKASA PURA KARGO" },
        { value: "TRMA", label: "APKI - ANGKASA PURA KARGO" },
        { value: "UTPK", label: "APRI - TPS-PT. ANGKASA PURA II - IMPOR" },
        { value: "WIRA", label: "KENA - PT KARGO EXPRESS NUSANTARA" },
        { value: "T007", label: "LE01 - TPS LINTAS EKSPRES N.C." },
        { value: "T303", label: "LOGW - TPS-TNS GUDANG LOGWIN AIR & OCEAN INDONESIA" },
        { value: "TER3", label: "LWPH - PT Logwin Air And Ocean Indonesia" },
        { value: "PRJP", label: "MATR - MITRA ATLANTIK TRANSINDO" },
  ],
  IDTPE: [
    { value: "BOGA", label: "BML1 - PT BERDIRI MATAHARI LOGISTIK" },
        { value: "BTTL", label: "CAR1 - PT CARDIG INTERNASIONAL SUPPORT" },
        { value: "CALN", label: "CIMP - GUDANG CARDIG IMPOR" },
        { value: "CEGI", label: "CJGL - CJ-GLS" },
        { value: "CIJS", label: "CLI1 - TPS-TNS CITRABATI LOGISTIK INTERNASIONAL" },
        { value: "CJAM", label: "GAJT - GARUDA INDONESIA PJT" },
        { value: "CKPL", label: "GATE - GHITA AVIA TRANS" },
        { value: "CLOG", label: "GATI - GHITA AVIA TRANS" },
        { value: "CMBA", label: "GBDL - PT. BANGUN DESA LOGISTINDO" },
        { value: "CMSB", label: "GBGD - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "CPSI", label: "GBGF - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "CPSU", label: "GBGT - GUDANG BANTEN GLOBAL DEVELOPMENT" },
        { value: "CTPS", label: "GCPL - GUDANG C & P LOGISTICS INDONES" },
        { value: "CTTL", label: "GDHL - GUDANG DHL" },
        { value: "GACS", label: "GDJT - WAHANA DIRGANTARA INDONESIA" },
        { value: "GALN", label: "GDWD - Gudang Wahan Dirgantara" },
        { value: "GBJT", label: "GDWF - GUDANG WAHANA DIRGANTARA INDONESIA" },
        { value: "GDIJ", label: "GDWI - GUDANG WAHANA DIRGANTARA IMPOR" },
        { value: "GEGI", label: "GELK - GARUDA ENERGI LOGISTIK KOMERSIAL" },
        { value: "GICT", label: "GGMF - GARUDA MAINTENANCE FACILITIES" },
        { value: "GJAM", label: "GGWI - GUDANG GEODIS WILSON INDONESIA" },
        { value: "GKPL", label: "GIBS - TPS-TNS INTI BANGUN SELARAS" },
        { value: "GMBA", label: "GIMP - GUDANG GARUDA IMPOR" },
        { value: "GPSU", label: "GJDC - TPS-TNS DHL PT. BIROTIKA SEMESTA" },
        { value: "GTTL", label: "GLFC - TPS-TNS GLOBAL FREIGHT CONSOLIDATAMA" },
        { value: "SSSC", label: "DS02 - PT DSV TRANSPORT INDONESIA" },
        { value: "PLPA", label: "DS03 - PT DSV TRANSPORT INDONESIA" },
  ],
    IDSUB: [
        { value: "GPOS", label: "GPOS - Gudang PT. Pos Indonesia" },
        { value: "GAPL", label: "GAPL - Gudang PT. Angkasa Pura Logistik" },
        { value: "G003", label: "G003 - G003" },
        { value: "JIMP", label: "JIMP - Gudang PT Jasa Angkasa Semesta Impor" },
        { value: "JEXP", label: "JEXP - Gudang PT Jasa Angkasa Semesta Ekspor"},
    ]

};

export default TPS_BY_PELABUHAN;