export const ListDokumen = [
            { key: "10", value: "RKSP" },
            { key: "11", value: "MANIFES" },
            { key: "16", value: "BC 1.6 - PEMBERITAHUAN PABEAN PENGELUARAN BARANG DARI KAWASAN PABEAN UNTUK DITIMBUN DI PUSAT LOGISTIK BERIKAT" },
            { key: "20", value: "BC 2.0 - PEMBERITAHUAN IMPOR BARANG" },
            { key: "21", value: "PIBK/IMPOR KHUSUS" },
            { key: "23", value: "BC 2.3 - PEMBERITAHUAN IMPOR BARANG UNTUK DITIMBUN DI TEMPAT PENIMBUNAN BERIKAT" },
            { key: "25", value: "BC 2.5 - PEMBERITAHUAN IMPOR BARANG DARI TEMPAT PENIMBUNAN BERIKAT" },
            { key: "27", value: "BC 2.7 - PEMBERITAHUAN PENGELUARAN UNTUK DIANGKUT DARI TEMPAT PENIMBUNAN BERIKAT KE TEMPAT PENIMBUNAN BERIKAT LAINNYA" },
            { key: "28", value: "BC 2.8 - PEMBERITAHUAN IMPOR BARANG DARI PUSAT LOGISTIK BERIKAT" },
            { key: "30", value: "BC 3.0 - PEMBERITAHUAN EKSPOR NARAMG" },
            { key: "33", value: "BC 3.3 - PEMBERITAHUAN EKSPOR BARANG MELALUI/DARI PUSAT LOGISTIK BERIKAT" },
            { key: "40", value: "BC 4.0 - PEMBERITAHUAN PEMASUKAN BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN KE TEMPAT PENIMBUNAN BERIKAT" },
            { key: "41", value: "BC 4.1 - PEMBERITAHUAN PENGELUARAN KEMBALI BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN DARI TEMPAT PENIMBUNAN BERIKAT" },
            { key: "50", value: "KITE" },
            { key: "51", value: "FTZ 01" },
            { key: "52", value: "FTZ 02" },
            { key: "53", value: "FTZ 03" },
            { key: "65", value: "BC 1.1 KONSOLIDASI PJT" },
            { key: "111", value: "Bank Devisa Hasil Ekspor (DHE)" },
            { key: "161", value: "PPB - PEMBERITAHUAN PERPINDAHAN BARANG ANTAR TEMPAT PENIMBUNAN DALAM SATU PUSAT LOGISTIK BERIKAT" },
            { key: "202", value: "PENGELUARAN BAHAN BAKU DAN/ ATAU SISA BAHAN BAKU" },
            { key: "203", value: "PENGELUARAN SEMENTARA - SUBKONTRAK" },
            { key: "204", value: "PENGELUARAN SEMENTARA - PERBAIKAN/ REPARASI" },
            { key: "205", value: "PENGELUARAN SEMENTARA - PEMINJAMAN BARANG MODAL UNTUK KEPERLUAN PRODUKSI" },
            { key: "206", value: "PENGELUARAN SEMENTARA - PENGETESAN ATAU PENGEMBANGAN KUALITAS PRODUKSI" },
            { key: "207", value: "PENGELUARAN SEMENTARA - PENGGUNAAN KEMASAN YANG DIPAKAI BERULANG (RETURNABLE PACKAGE)" },
            { key: "208", value: "PENGELUARAN SEMENTARA - DIPAMERKAN" },
            { key: "209", value: "PENGELUARAN SEMENTARA - TUJUAN LAIN DENGAN PERSETUJUAN KEPALA KANTOR PABEAN" },
            { key: "210", value: "PENERIMAAN PEKERJAAN - SUBKONTRAK" },
            { key: "211", value: "PENERIMAAN PEKERJAAN - PERBAIKAN/ REPARASI" },
            { key: "212", value: "PENERIMAAN PEKERJAAN - PEKERJAAN LAIN" },
            { key: "213", value: "PEMUSNAHAN BARANG DI KAWASAN BERIKAT" },
            { key: "217", value: "PACKING LIST" },
            { key: "246", value: "L/C" },
            { key: "261", value: "BC 2.6.1 - PEMBERITAHUAN PENGELUARAN BARANG DARI TEMPAT PENIMBUNAN BERIKAT DENGAN JAMINAN" },
            { key: "262", value: "BC 2.6.2 - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG YANG DI KELUARKAN DARI TEMPAT PENIMBUNAN BERIKAT DENGAN JAMINAN" },
            { key: "281", value: "PPK - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG ASAL PLB DARI LOKASI PENERIMA FASILITAS DI TEMPAT LAIN DALAM DAERAH PABEAN KE PLB" },
            { key: "282", value: "DOKAP PLB - PEMBERITAHUAN PENGELUARAN DENGAN DOKUMEN PELENGKAP" },
            { key: "302", value: "CN Ekspor" },
            { key: "315", value: "KONTRAK" },
            { key: "331", value: "P3BET - PEMBERITAHUAN PENGGABUNGAN DAN PEMECAHAN BARANG EKSPOR DAN TRANSHIPMENT" },
            { key: "343", value: "SHIPING ORDER" },
            { key: "380", value: "INVOICE" },
            { key: "383", value: "SSTB" },
            { key: "388", value: "FAKTUR PAJAK" },
            { key: "410", value: "SURAT SANGGUP BAYAR / SSB" },
            { key: "430", value: "BANK GARANSI" },
            { key: "440", value: "SURAT TANDA BUKTI SETOR / STBS" },
            { key: "454", value: "SSPCP / SSBC" },
            { key: "455", value: "SURAT SETORAN PAJAK (SSP)" },
            { key: "456", value: "SKB" },
            { key: "457", value: "Surat Keterangan Bebas (SKB) PPh" },
            { key: "458", value: "SURAT KETERANGAN TIDAK DIPUNGUT (SKTD) PPN" },
            { key: "459", value: "Non SKB / SKTD" },
            { key: "500", value: "MOU PDE (Eksportir)" },
            { key: "511", value: "FTZ-01 PEMASUKAN DARI LUAR DAERAH PABEAN (IMPOR)" },
            { key: "512", value: "FTZ-01 PENGELUARAN KE LUAR DAERAH PABEAN (EKSPOR)" },
            { key: "513", value: "FTZ-01 PENGELUARAN KE TEMPAT LAIN DALAM DAERAH PABEAN" },
            { key: "521", value: "FTZ-02 PEMASUKAN ANTAR FREE TRADE ZONE DAN KAWASAN BERIKAT" },
            { key: "522", value: "FTZ-02 PENGELUARAN ANTAR FREE TRADE ZONE DAN KAWASAN BERIKAT" },
            { key: "531", value: "FTZ-03 PEMASUKAN DARI TEMPAT LAIN DALAM DAERAH PABEAN" },
            { key: "640", value: "DELIVERY ORDER" },
            { key: "666", value: "Pengecualian Dengan Surat Keputusan" },
            { key: "704", value: "MASTER B/L" },
            { key: "705", value: "B/L" },
            { key: "740", value: "AWB" },
            { key: "741", value: "MASTER AWB" },
            { key: "800", value: "SERTIFIKAT ALAT PERANGKAT TELEKOM/POSTEL" },
            { key: "803", value: "SATS LN / DEPHUT" },
            { key: "805", value: "REGISTRASI B3 / KLH" },
            { key: "808", value: "IJIN IMPOR / POLRI" },
            { key: "809", value: "SIE" },
            { key: "810", value: "SM/SPM" },
            { key: "811", value: "Sertifikat Legalitas Kayu (Dok.V-Legal)" },
            { key: "812", value: "Dok. Impor (PIB)" },
            { key: "813", value: "DOK. CUKAI (CK)" },
            { key: "814", value: "SKEP IJIN EKSPOR BERKALA" },
            { key: "815", value: "SKEP IJIN TATA NIAGA EKSPOR" },
            { key: "816", value: "DOK. EKSPOR (PEB)" },
            { key: "817", value: "Eksportir Terdaftar (ET) Depdag" },
            { key: "818", value: "Endorsement BRIK" },
            { key: "819", value: "Sertifikat Intan Kasar" },
            { key: "820", value: "Surat Persetujuan Ekspor (SPE)" },
            { key: "821", value: "Surat Tanda Registrasi UPPB" },
            { key: "822", value: "Srt Tanda Pendaftaran Pedagang Bokor SIR" },
            { key: "834", value: "SNI GULA KRISTAL MENTAH / DEPTAN" },
            { key: "835", value: "IZIN DAN/ATAU PENDAFT PESTISIDA / DEPTAN" },
            { key: "836", value: "IZIN IMPOR / DEPTAN" },
            { key: "842", value: "SNI / ESDM" },
            { key: "843", value: "NOMOR PELUMAS TERDAFTAR / ESDM" },
            { key: "844", value: "IJIN USAHA NIAGA/IU NIAGA TERBATAS/ESDM" },
            { key: "845", value: "REKOMENDASI IMPOR PELUMAS" },
            { key: "846", value: "SKEM" },
            { key: "851", value: "SURAT IJIN KARANTINA TANAMAN" },
            { key: "853", value: "SURAT IJIN KARANTINA HEWAN / IKAN" },
            { key: "854", value: "SURAT PERSETUJUAN MUAT BPOM" },
            { key: "856", value: "LAP. PEMERIKSAAN SURVEYOR (LPS-E)" },
            { key: "857", value: "FUMIGATION CERTIFICATE" },
            { key: "858", value: "CITES CERTIFICATE" },
            { key: "860", value: "Electronic Certificate Of Origin (E-CO)" },
            { key: "861", value: "CERTIFICATE OF ORIGIN (CO)" },
            { key: "862", value: "SKEP USDFS" },
            { key: "871", value: "Nomor Pendaftaran Alat Kesehatan/Depkes" },
            { key: "872", value: "LAPORAN SURVEYOR DEPKES" },
            { key: "873", value: "IP (NARKTK, PREKURSOR & PSIKOTR)/DEPKES" },
            { key: "874", value: "IT (PREKURSOR & PSIKOTR)/DEPKES" },
            { key: "875", value: "SPI (NARKTK, PREKURSOR & PSIKOTR)/DEPKES" },
            { key: "876", value: "Ijin Pembawaan UKA" },
            { key: "877", value: "Ijin Persetujuan Pembawaan UKA" },
            { key: "878", value: "Ijin Pelaporan Pembawaan UKA" },
            { key: "888", value: "PENGECUALIAN PERIJINAN" },
            { key: "902", value: "IJIN BAPETEN" },
            { key: "911", value: "SURAT KEPUTUSAN" },
            { key: "912", value: "SKEP FASILITAS BKPM" },
            { key: "913", value: "SKEP FASILITAS PERTAMBANGAN" },
            { key: "914", value: "KITE IKM" },
            { key: "915", value: "Skep Fasilitas Impor Sementara" },
            { key: "917", value: "BPBC / BPPAI" },
            { key: "918", value: "SK LABEL BAHASA INDONESIA" },
            { key: "919", value: "SK Bermotor" },
            { key: "920", value: "SKEP TPB" },
            { key: "936", value: "KH-9a/Izin Impor Karantina Hewan" },
            { key: "937", value: "KH-14/Izin Impor Karantina Hewan" },
            { key: "938", value: "KH-17/Izin Impor Karantina Hewan" },
            { key: "939", value: "KT-5/Izin Impor Karantina Pertanian" },
            { key: "940", value: "KT-9/Izin Impor Karantina Pertanian" },
            { key: "941", value: "KT-13/Izin Impor Karantina Pertanian" },
            { key: "942", value: "IZIN IMPOR KARANTINA TUMBUHAN" },
            { key: "943", value: "KH-5 / IZIN IMPOR KARANTINA HEWAN" },
            { key: "944", value: "KH-7 / IZIN IMPOR KARANTINA HEWAN" },
            { key: "945", value: "KH-12 / IZIN IMPOR KARANTINA HEWAN" },
            { key: "946", value: "KID-3 / IZIN IMPOR KARANTINA IKAN" },
            { key: "947", value: "KID-15 / IZIN IMPOR KARANTINA IKAN" },
            { key: "948", value: "NPIK" },
            { key: "949", value: "PENGAKUAN SBG IMPORTIR PRODUSEN" },
            { key: "950", value: "KID-4/IZIN KARANTINA IKAN" },
            { key: "951", value: "HC (HEALTH CERTIFICATE)" },
            { key: "956", value: "PENGAKUAN SBG IMPORTIR TERDAFTAR" },
            { key: "957", value: "SNI/SPB/DEPDAG" },
            { key: "958", value: "LAPORAN SURVEYOR / DEPDAG" },
            { key: "959", value: "SURAT PERSETUJUAN IMPOR DEP.DAG" },
            { key: "960", value: "3D/PC dan/atau PFP" },
            { key: "961", value: "Hasil Lab" },
            { key: "993", value: "SURAT IJIN MENTERI PERTANIAN" },
            { key: "994", value: "BUKTI PENERIMAAN JAMINAN (BPJ)" },
            { key: "995", value: "STBS / SSP-E (PAJAK EKSPOR)" },
            { key: "996", value: "SRT SANGGUP BAYAR (SSB)" },
            { key: "997", value: "COSTOMS BOND / STTJ" },
            { key: "998", value: "SKEP FASILITAS KEMUDAHAN EKSPOR" },
            { key: "999", value: "LAINNYA" },
            { key: "03001", value: "Izin Prinsip Pendirian Kawasan Berikat Sebelum Fisik Bangunan Berdiri" },
            { key: "03002", value: "Keputusan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan Berikat" },
            { key: "03003", value: "Persetujuan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan Berikat Sekaligus Izin Pengusaha Kawasan Berikat" },
            { key: "03004", value: "Izin PDKB" },
            { key: "03005", value: "Perpanjangan Penetapan Tempat Sebagai Kawasan Berikat Dan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB Sebelum Jangka Waktu Izin Tersebut Berakhir" },
            { key: "03006", value: "Perubahan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB (Terdapat Perubahan Nama Perusahaan Yang Bukan Dikarenakan Merger Atau Diakuisisi, Jenis Hasil Produksi, Atau Luas Kawasan Berikat)" },
            { key: "03007", value: "Perubahan Keputusan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB" },
            { key: "03008", value: "Pemberian Izin Penambahan Pintu Khusus Pemasukan Dan Pengeluaran Barang Di Kawasan Berikat" },
            { key: "03009", value: "Pemberian Izin Penambahan Pintu Khusus Orang Di Kawasan Berikat" },
            { key: "03010", value: "Persetujuan Pemasukan Barang Dari Kawasan Bebas Ke Kawasan Berikat" },
            { key: "03011", value: "Persetujuan Pemasukan Barang Modal Dari Luar Daerah Pabean" },
            { key: "03012", value: "Persetujuan Pemasukan Barang Modal Dari Kawasan Berikat Lain" },
            { key: "03013", value: "Persetujuan Pemasukan Barang Jadi Asal Luar Daerah Pabean Untuk Digabungkan Dengan Hasil Produksi Utama Kawasan Berikat" },
            { key: "03014", value: "Persetujuan Pemasukan Peralatan Perkantoran Asal Luar Daerah Pabean Ke Kawasan Berikat" },
            { key: "03015", value: "Persetujuan Pemasukan Barang Contoh Asal Luar Daerah Pabean" },
            { key: "03016", value: "Persetujuan Pembebasan Bea Masuk Untuk Barang Contoh Yang Akan Dikeluarkan Ke Tempat Lain Dalam Daerah Pabean" },
            { key: "03017", value: "Persetujuan Mengeluarkan Hasil Produksi Kawasan Berikat Ke Tempat Penyelenggaraan Pameran Berikat (TPPB)" },
            { key: "03018", value: "Persetujuan Untuk Mengeluarkan Bahan Baku Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Yang Sama Sekali Tidak Diproses Ke Gudang Berikat Asal Barang" },
            { key: "03019", value: "Persetujuan Untuk Mengeluarkan Barang Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Asal Tlddp Ke TLDDP" },
            { key: "03020", value: "Persetujuan Pengeluaran Bahan Baku/Sisa Bahan Baku Asal Impor Untuk Direekspor" },
            { key: "03021", value: "Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Kawasan Berikat Lain" },
            { key: "03022", value: "Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Perusahaan Industri Di TLDDP" },
            { key: "03023", value: "Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu Manajemen" },
            { key: "03024", value: "Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu PKB" },
            { key: "03025", value: "Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lainnya" },
            { key: "03026", value: "Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Dibayar BM-nya Untuk Direekspor" },
            { key: "03027", value: "Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM-nya Ke Kawasan Berikat Lain Setelah Jangka Waktu 2 (Dua) Tahun Sejak Diimpor Dan Telahdipergunakan Di Kawasan Berikat" },
            { key: "03028", value: "Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM Ke Tempat Lain Dalam Daerah Pabean Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat" },
            { key: "03029", value: "Keputusan Pembebasan BM Atas Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat" },
            { key: "03030", value: "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Lunas BM Untuk Direekspor" },
            { key: "03031", value: "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke Kawasan Berikat Lain Setelah Dipergunakan Di Kawasan Berikat" },
            { key: "03032", value: "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke TLDDP Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat Yang Bersangkutan" },
            { key: "03033", value: "Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat" },
            { key: "03034", value: "Persetujuan Untuk Memindahtangankan Barang Modal Dan/Atau Peralatan Perkantoran Yang Telah Dilunasi BM Dan PDRI Pada Saat Pemasukan Ke Kawasan Berikat" },
            { key: "03035", value: "Persetujuan Untuk Memindahtangankan Barang Modal Asal Tempat Lain Dalam Daerah Pabean" },
            { key: "03036", value: "Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke Luar Daerah Pabean" },
            { key: "03037", value: "Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke TLDDP" },
            { key: "03038", value: "Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke KB Lain" },
            { key: "03039", value: "Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke TLDDP" },
            { key: "03040", value: "Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke KB Lain" },
            { key: "03041", value: "Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke TLDDP" },
            { key: "03042", value: "Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke PDKB Lain" },
            { key: "03043", value: "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Dalam Rangka Subkontrak" },
            { key: "03044", value: "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Bukan Dalam Rangka Subkontrak" },
            { key: "03045", value: "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Dalam Rangka Subkontrak" },
            { key: "03046", value: "Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Bukan Dalam Rangka Subkontrak" },
            { key: "03047", value: "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Dalam Rangka Subkontrak" },
            { key: "03048", value: "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Bukan Dalam Rangka Subkontrak" },
            { key: "03049", value: "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Dalam Rangka Subkontrak" },
            { key: "03050", value: "Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Selain Dalam Rangka Subkontrak" },
            { key: "03051", value: "Persetujuan Peminjaman Mesin Atau Cetakan (Moulding) Yang Melebihi Jangka Waktu" },
            { key: "03052", value: "Persetujuan Pemusnahan Atas Barangbarang Yang Busuk Dan/Atau Yang Karena Sifat Dan Bentuknya Dapat Dimusnahkan" },
            { key: "03053", value: "Persetujuan Perusakan Atas Barang Asal Luar Daerah Pabean Yang Karena Sifat Dan Bentuknya Tidak Dapat Dimusnahkan" },
            { key: "03054", value: "Persetujuan Menerima Subkontrak Dari TLDDP" },
            { key: "03055", value: "Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Dalam Rangka Subkontrak" },
            { key: "03056", value: "Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Bukan Dalam Rangka Subkontrak" },
            { key: "03057", value: "Persetujuan Peminjaman Mesin/Peralatan Pabrik Dari TLDDP" },
            { key: "03060", value: "Persetujuan Pemasukan Barang Modal Berupa Peralatan Pabrik Dari Luar Daerah Pabean" },
            { key: "03061", value: "Persetujuan Pemasukan Barang Modal Berupa Suku Cadang Dari Luar Daerah Pabean Yang Dimasukkan Tidak Bersamaan Dengan Barang Modal" },
            { key: "03062", value: "Persetujuan Pemasukan Kembali (Reimpor) Barang Hasil Produksi Asal TPB" },
            { key: "03063", value: "Persetujuan Pemasukan Kembali (Reimpor) Barang Modal Setelah Perbaikan/Reparasi Dari Luar Daerah Pabean" },
            { key: "03064", value: "Persetujuan Perpanjangan Jangka Waktu Pengeluaran Barang Modal Keperluan Perbaikan/Reparasi Tujuan TLDDP" },
            { key: "03065", value: "Persetujuan Pengeluaran Barang Contoh/Sampel KB Dengan Tujuan TLDDP" },
            { key: "03066", value: "Rekomendasi Meminjamkan Barang Modal Ke TLDDP Dalam Rangka Subkontrak Atau Bukan Lebih Dari 6 Bulan" }
        ]