import type { Barang, BarangTarif } from "../BC23.types";

export const createInitialBarang = (): Barang => ({
  idBarang: null,
  asuransi: 0,
  cif: 0,
  diskon: 0,
  fob: 0,
  freight: 0,
  hargaEkspor: 0,
  hargaPenyerahan: 0,
  hargaSatuan: 0,
  isiPerKemasan: 0,
  jumlahKemasan: 0,
  jumlahSatuan: 0,
  kodeBarang: null,
  kodeDokumen: null,
  kodeKategoriBarang: null,
  kodeJenisKemasan: null,
  kodeNegaraAsal: null,
  kodePerhitungan: "0",
  kodeSatuanBarang: null,
  merk: null,
  netto: 0,
  nilaiBarang: 0,
  nilaiTambah: 0,
  posTarif: null,
  seriBarang: 0,
  spesifikasiLain: null,
  tipe: null,
  ukuran: null,
  uraian: null,
  ndpbm: 0,
  cifRupiah: 0,
  hargaPerolehan: 0,
  kodeAsalBahanBaku: "0",
  barangTarif: [],
  barangDokumen: []
});

export const createInitialBarangTarif = (): BarangTarif[] => [{
  kodeJenisTarif: "1",
  jumlahSatuan: 0,
  kodeFasilitasTarif: null,
  kodeSatuanBarang: null,
  kodeJenisPungutan: null,
  nilaiBayar: 0,
  nilaiFasilitas: 0,
  nilaiSudahDilunasi: 0,
  seriBarang: 0,
  tarif: 0,
  tarifFasilitas: 0
}];