import type { BC23Request } from "../BC23.types";

export const defaultBC23Request: BC23Request = {
  asalData: "S",
  asuransi: 0,
  bruto: 0,
  cif: 0,
  fob: 0,
  freight: 0,
  hargaPenyerahan: 0,
  jabatanTtd: "",
  jumlahKontainer: 0,
  kodeAsuransi: "LN",
  kodeDokumen: "23",
  kodeIncoterm: "",
  kodeKantor: "",
  kodeKantorBongkar: "",
  kodePelBongkar: "",
  kodePelMuat: "",
  kodePelTransit: "",
  kodeTps: "",
  kodeTujuanTpb: "",
  kodeTutupPu: "11",
  kodeValuta: "",
  kotaTtd: "",
  namaTtd: "",
  ndpbm: 0,
  netto: 0,
  nik: "",
  nilaiBarang: 0,
  nomorAju: "",
  nomorBc11: "",
  posBc11: "",
  seri: 0,
  subposBc11: "",
  tanggalBc11: "",
  tanggalTiba: "",
  tanggalTtd: "",
  biayaTambahan: 0,
  biayaPengurang: 0,
  kodeKenaPajak: "1",

  barang: [],
  entitas: [],
  kemasan: [],
  kontainer: [],
  dokumen: [],
  pengangkut: []
};