import moment from "moment";
import type { BC23Request } from "../BC23.types";

export const defaultBC23Request: BC23Request = {
  asalData: "S",
  asuransi: 0,
  bruto: 0,
  cif: 0,
  fob: 0,
  freight: 0,
  hargaPenyerahan: 0,
  jabatanTtd: "KASIE KEPABEANAN",
  jumlahKontainer: 0,
  kodeAsuransi: "LN",
  kodeDokumen: "23",
  kodeIncoterm: "",
  kodeKantor: "",
  kodeKantorBongkar: "",
  kodePelBongkar: "",
  kodePelMuat: "",
  kodePelTransit: "",
  kodeTps: "",
  kodeTujuanTpb: "",
  kodeTutupPu: "11",
  kodeValuta: "",
  kotaTtd: "SUKOHARJO",
  namaTtd: "UDIK WIJANARKO",
  ndpbm: 0,
  netto: 0,
  nik: "",
  nilaiBarang: 0,
  nomorAju: "",
  nomorBc11: "",
  posBc11: "",
  seri: 0,
  subposBc11: "",
  tanggalBc11:moment(new Date()).format("YYYY-MM-DD"),
  tanggalTiba: null,
  tanggalTtd: moment(new Date()).format("YYYY-MM-DD"),
  biayaTambahan: 0,
  biayaPengurang: 0,
  kodeKenaPajak: "1",

  barang: [],
  entitas: [],
  kemasan: [],
  kontainer: [],
  dokumen: [],
  pengangkut: []
};